import AddIcon from '@mui/icons-material/Add'
import EditIcon from '@mui/icons-material/Edit'
import FavoriteIcon from '@mui/icons-material/Favorite'
import NavigationIcon from '@mui/icons-material/Navigation'
import Box from '@mui/material/Box'
import Fab from '@mui/material/Fab'
import { StyledEngineProvider } from '@mui/material/styles'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        <StyledEngineProvider injectFirst>
          <Box sx={{ '& > :not(style)': { m: 1 } }}>
            <Fab className='bg-blue-700 hover:bg-red-600' aria-label='add'>
              <AddIcon />
            </Fab>
            <Fab aria-label='edit'>
              <EditIcon />
            </Fab>
            <Fab variant='extended'>
              <NavigationIcon sx={{ mr: 1 }} />
              Navigate
            </Fab>
            <Fab disabled aria-label='like'>
              <FavoriteIcon />
            </Fab>
          </Box>
        </StyledEngineProvider>
      </main>
    </>
  )
}
