import Categories from '@/components/Categories'
import CourseCard from '@/components/CourseCard'
import DesktopNav from '@/components/DesktopNav'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Instructors from '@/components/Instructors'
import Testimonial from '@/components/testimonial'
import Head from 'next/head'
import { getCourses } from '../../utils/db'

export default function Home(courses) {
  return (
    <>
      <Head>
        <title>Skills Builder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='mx-auto flex max-w-[1440px] flex-col gap-24 bg-primary p-10'>
        <DesktopNav />
        <div className='flex flex-wrap'></div>
        {/* <AllCourses courses={courses} /> */}
        <Header />
        <Categories />
        <CourseCard courses={courses} />
        <Instructors />
        <Testimonial />
        <Footer />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await getCourses()

  return {
    props: {
      courses: JSON.parse(JSON.stringify(data)),
    },
  }
}
