import Categories from '@/components/Categories'
import CourseCard from '@/components/CourseCard'
import DesktopNav from '@/components/DesktopNav'
import FeaturedCourses from '@/components/FeaturedCourses'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Instructors from '@/components/Instructors'
import Testimonial from '@/components/testimonial'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Skills Builder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col gap-24 bg-primary p-10'>
        <DesktopNav />
        <Header />
        <Categories />
        <FeaturedCourses />
        <CourseCard />
        <Instructors />
        <Testimonial />
        <Footer />
      </main>
    </>
  )
}
